version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    volumes:
      - ./app:/app
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - postgresql-db

  postgresql-db:
    image: postgres:latest
    container_name: postgres-container
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pg_data:
